import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { monserratFont } from "@/helpers/customFonts";
import InputText from "@/components/atomic/Input/InputText";
import { useState } from "react";
import * as formik from "formik";
import * as Yup from "yup";
import { Button, Form } from "react-bootstrap";

export default function Home() {
  const { Formik } = formik;
  //validation schema
  const validationSchema = Yup.object({
    email: Yup.string().email().required("Email is required"),
    password: Yup.string().required("Password is required"),
  });

  //password visibility
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);
  const togglePasswordVisibility = () => {
    setIsPasswordVisible((prevState) => !prevState);
  };

  return (
    <>
      <Head>
        <title>Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${monserratFont.className}`}>
        <div>
          <p>Test Form</p>
          <Formik
            initialValues={{ email: "", password: "" }}
            onSubmit={console.log}
            validationSchema={validationSchema}
          >
            {({
              handleBlur,
              handleChange,
              handleSubmit,
              values,
              errors,
              touched,
            }) => (
              <Form>
                <InputText
                  title="Email"
                  type="email"
                  name="email"
                  placeholder="Masukkan Email"
                  value={values.email}
                  onChange={handleChange}
                  isInvalid={!!errors.email}
                  errorText={errors.email}
                />
                <InputText
                  title="Password"
                  type={isPasswordVisible ? "text" : "password"}
                  name="password"
                  placeholder="Masukkan Password"
                  value={values.password}
                  onChange={handleChange}
                  isInvalid={!!errors.password}
                  errorText={errors.password}
                  viewEyeIcon
                  eyeIcon={
                    isPasswordVisible
                      ? `assets/icons/Eye-visible.svg`
                      : `assets/icons/Eye-invisible.svg`
                  }
                  togglePasswordVisibility={togglePasswordVisibility}
                />
                <Form.Group className="mb-3">
                  <Form.Check required label="Remember Me" />
                </Form.Group>
                <Button type="submit">Login</Button>
              </Form>
            )}
          </Formik>
        </div>
      </main>
    </>
  );
}
